name: safenest
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.6
  get: ^4.6.6
  get_it: ^7.7.0
  page_transition: ^2.1.0
  firebase_core: ^3.3.0
  uuid: ^4.4.2
  dartz: ^0.10.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  hive: ^4.0.0-dev.2
  equatable: ^2.0.5
  flutter_animate: ^4.5.0
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.2.0+3
  firebase_storage: ^12.1.3
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1
  iconly: ^1.0.1
  rxdart: ^0.28.0
  dio: ^5.6.0
  http_interceptor: ^2.0.0
  riverpod: ^2.5.1
  cached_network_image: ^3.4.0
  shimmer: ^3.0.0
  percent_indicator: ^4.2.3
  geocoding: ^3.0.0
  google_maps_flutter: ^2.6.1
  geolocator: ^12.0.0
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^17.2.2
  flutter_background_service: ^5.0.9
  intl: ^0.19.0
  app_usage: ^3.0.1
  image_picker: ^1.1.2
  location: ^6.0.2
  lottie: ^3.1.2
  usage_stats: ^1.2.0
  swipe_cards: ^2.0.0+1
  pinput: ^5.0.0
  qr_flutter: ^4.1.0
  qr_bar_code: ^1.3.0
  fl_chart: ^0.69.0
  mobile_scanner: ^5.0.0
  table_calendar: ^3.0.9
  syncfusion_flutter_charts: ^26.2.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.0.0+1
  google_sign_in_mocks: ^0.3.0
  envied_generator: ^0.5.3
  build_runner: ^2.4.6
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/lottie/
    - assets/vectors/
    - assets/icons/
    - assets/lang/
