// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwChcbW0CnRa97yrv9IEMzgdCdpwsN5y0',
    appId: '1:545427401569:web:95d73fb9b14f495b78b320',
    messagingSenderId: '545427401569',
    projectId: 'safenest-e077e',
    authDomain: 'safenest-e077e.firebaseapp.com',
    storageBucket: 'safenest-e077e.appspot.com',
    measurementId: 'G-7J9028WMQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_u32DVRntOCzU0YQr0mwclV1FOgTC1Bo',
    appId: '1:545427401569:android:0f94f9debb96ac2a78b320',
    messagingSenderId: '545427401569',
    projectId: 'safenest-e077e',
    storageBucket: 'safenest-e077e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuGxBPBlvo3gnuRliTFRO0st8vgDm_9Ic',
    appId: '1:545427401569:ios:d6e134af94d8e42078b320',
    messagingSenderId: '545427401569',
    projectId: 'safenest-e077e',
    storageBucket: 'safenest-e077e.appspot.com',
    iosBundleId: 'com.neuslabs.safenest',
  );
}
